-- ======================================================
-- Project: Guided Tours Management System
-- Description: Cleanup script to drop all tables
-- Note: Tables are dropped in reverse order of creation
-- to handle foreign key dependencies.
-- ======================================================

DROP TABLE IF EXISTS PASSES_THROUGH CASCADE;
DROP TABLE IF EXISTS REGISTRATION_AUDIT CASCADE;
DROP TABLE IF EXISTS PAYMENT CASCADE;
DROP TABLE IF EXISTS REGISTRATION CASCADE;
DROP TABLE IF EXISTS PARTICIPANT CASCADE;
DROP TABLE IF EXISTS GUIDEDTOUR CASCADE;
DROP TABLE IF EXISTS REGISTRATIONSTATUS CASCADE;
DROP TABLE IF EXISTS PAYMENTSTATUS CASCADE;
DROP TABLE IF EXISTS TOURSTATUS CASCADE;
DROP TABLE IF EXISTS GUIDE CASCADE;
DROP TABLE IF EXISTS ROUTE CASCADE;
DROP TABLE IF EXISTS DIFFICULTYLEVEL CASCADE;
DROP TABLE IF EXISTS LOCATION CASCADE;
