-- ======================================================






-- Project: Guided Tours Management System
-- Phase 3: Integration (Integrate.sql)


   
-- 1. Adaptation des colonnes de la table Route
ALTER TABLE route RENAME COLUMN duration TO estimatedduration;
ALTER TABLE route ADD COLUMN estimatedlenght FLOAT;
ALTER TABLE route ADD COLUMN description TEXT;

-- 2. CRÉATION de la table de référence (C'est ça qui manquait !)
CREATE TABLE difficultylevel (
    difficultyid SERIAL PRIMARY KEY,
    difficultyname VARCHAR(50) UNIQUE NOT NULL
);

-- 3. Remplissage avec les niveaux de DB2 + ton "Extreme" de DB1
INSERT INTO difficultylevel (difficultyname) VALUES 
('Easy'), 
('Moderate'), 
('Hard'), 
('Advanced'), 
('Expert'),
('Extreme');

-- 4. Création du lien dans Route (Clé Étrangère)
ALTER TABLE route ADD COLUMN difficulty_id_fk INT REFERENCES difficultylevel(difficultyid);

-- 5. MISE À JOUR DES DONNÉES (Le mapping)
-- Easy reste Easy (ID 1)
UPDATE route SET difficulty_id_fk = 1 WHERE difficulty = 'Easy';

-- Medium devient Moderate (ID 2)
UPDATE route SET difficulty_id_fk = 2 WHERE difficulty = 'Medium';

-- Hard reste Hard (ID 3)
UPDATE route SET difficulty_id_fk = 3 WHERE difficulty = 'Hard';

-- Extreme pointe vers Extreme (ID 6, car c'est le 6ème inséré)
UPDATE route SET difficulty_id_fk = 6 WHERE difficulty = 'Extreme';

-- 6. Nettoyage : On supprime l'ancienne colonne
ALTER TABLE route DROP COLUMN difficulty;






---------------------------------------------------------------------------------------
-- DÉCISION 5 : FUSION DES TABLES PARTICIPANT (DB1) ET CUSTOMER (DB2)
-- Objectif : Harmoniser les données clients sous l'entité unique "Participant".
-- La structure finale conserve 'FullName' et intègre 'JoinDate' provenant de DB2.
---------------------------------------------------------------------------------------

-- 1. ADAPTATION DE LA STRUCTURE (DB1)
-- On ajoute la colonne 'JoinDate' qui n'existait pas dans notre base d'origine.
-- Elle est de type DATE pour correspondre aux données du Groupe 2.
ALTER TABLE participant ADD COLUMN JoinDate DATE;

-- 2. DOCUMENTATION DES DONNÉES EXISTANTES
-- Pour nos participants actuels (DB1), nous n'avons pas de date d'inscription.
-- On peut décider de mettre la date d'aujourd'hui par défaut pour ne pas avoir de [null].
UPDATE participant SET JoinDate = CURRENT_DATE WHERE JoinDate IS NULL;


---------------------------------------------------------------------------------------
-- LOGIQUE D'IMPORTATION DES DONNÉES DU GROUPE 2 (À titre informatif)
---------------------------------------------------------------------------------------
/* Pour importer leurs données depuis leur table 'customer' vers notre table 'participant' :
   
   INSERT INTO participant (FullName, Email, Phone, JoinDate)
   SELECT FullName, Email, Phone, JoinDate 
   FROM customer_from_db2; 
   
   Note : On laisse SQL gérer l'incrémentation automatique du 'ParticipantID' 
   pour éviter les conflits de clés primaires entre les deux groupes.
*/







/*-- Description: Updating existing DB schema without dropping existing tables.
-- integrating table representations generated by Reverse Engineering from 'stage2' DB.
-- ======================================================

-- -- 1. Integrate 'DIFFICULTYLEVEL' table references to 'ROUTE' --
CREATE TABLE DIFFICULTYLEVEL
(
    DifficultyID INT NOT NULL,
    DifficultyName VARCHAR(50) NOT NULL,
    PRIMARY KEY (DifficultyID)
);

-- Insert reference values (Based on Stage 2 existing records)
INSERT INTO DIFFICULTYLEVEL(DifficultyID, DifficultyName) VALUES(1, 'Easy');
INSERT INTO DIFFICULTYLEVEL(DifficultyID, DifficultyName) VALUES(2, 'Medium');
INSERT INTO DIFFICULTYLEVEL(DifficultyID, DifficultyName) VALUES(3, 'Hard');
INSERT INTO DIFFICULTYLEVEL(DifficultyID, DifficultyName) VALUES(4, 'Extreme');

-- Update 'ROUTE' table (From existing string Difficulty to DifficultyID)
ALTER TABLE ROUTE ADD COLUMN EstimatedLength NUMERIC(8,2) CHECK (EstimatedLength >= 0);
ALTER TABLE ROUTE ADD COLUMN Description VARCHAR(500);
ALTER TABLE ROUTE ADD COLUMN DifficultyID INT;

-- Data update: migrate the string Difficulty into matching DifficultyID (Optional but logical mapped data migration)
UPDATE ROUTE SET DifficultyID = 1 WHERE Difficulty = 'Easy';
UPDATE ROUTE SET DifficultyID = 2 WHERE Difficulty = 'Medium';
UPDATE ROUTE SET DifficultyID = 3 WHERE Difficulty = 'Hard';
-- Since 'Difficulty' is no longer needed (replaced by FK), we can drop it
ALTER TABLE ROUTE DROP COLUMN Difficulty;

-- Restore FK constraint
ALTER TABLE ROUTE ADD CONSTRAINT fk_route_difficulty FOREIGN KEY (DifficultyID) REFERENCES DIFFICULTYLEVEL(DifficultyID);


-- -- 2. Integrate 'GUIDE' properties --
ALTER TABLE GUIDE ADD COLUMN Email VARCHAR(100) UNIQUE;
ALTER TABLE GUIDE ADD COLUMN BirthDate DATE;
ALTER TABLE GUIDE ADD COLUMN JoinDate DATE;
ALTER TABLE GUIDE ADD COLUMN DailyRate NUMERIC(8,2) CHECK (DailyRate >= 0);
ALTER TABLE GUIDE ADD COLUMN ExperienceYears INT CHECK (ExperienceYears >= 0);
ALTER TABLE GUIDE ADD COLUMN Rating NUMERIC(3,2) CHECK (Rating BETWEEN 0 AND 5);
ALTER TABLE GUIDE ADD COLUMN Address VARCHAR(200);
ALTER TABLE GUIDE ADD COLUMN Notes VARCHAR(500);


-- -- 3. Integrate 'TOURSTATUS' and updates for 'TRIP' (GUIDEDTOUR in stage 2) --
CREATE TABLE TOURSTATUS
(
    TourStatusID INT NOT NULL,
    StatusName VARCHAR(50) NOT NULL,
    PRIMARY KEY (TourStatusID)
);

-- Insert reference data
INSERT INTO TOURSTATUS(TourStatusID, StatusName) VALUES(1, 'Planned');
INSERT INTO TOURSTATUS(TourStatusID, StatusName) VALUES(2, 'Open for Registration');
INSERT INTO TOURSTATUS(TourStatusID, StatusName) VALUES(3, 'Full');
INSERT INTO TOURSTATUS(TourStatusID, StatusName) VALUES(4, 'In Progress');
INSERT INTO TOURSTATUS(TourStatusID, StatusName) VALUES(5, 'Completed');
INSERT INTO TOURSTATUS(TourStatusID, StatusName) VALUES(6, 'Cancelled');

ALTER TABLE TRIP ADD COLUMN EndDate DATE;
ALTER TABLE TRIP ADD COLUMN StartTime VARCHAR(10);
ALTER TABLE TRIP ADD COLUMN EndTime VARCHAR(10);
ALTER TABLE TRIP ADD COLUMN MeetingPoint VARCHAR(200); -- NOT NULL normally, but added to existing so left nullable for initial migration
ALTER TABLE TRIP ADD COLUMN Notes VARCHAR(500);
ALTER TABLE TRIP ADD COLUMN TourStatusID INT;

-- Default tour status (assuming 1 is 'Planned') for old trips without status
UPDATE TRIP SET TourStatusID = 1 WHERE TourStatusID IS NULL;

ALTER TABLE TRIP ADD CONSTRAINT fk_trip_tourstatus FOREIGN KEY (TourStatusID) REFERENCES TOURSTATUS(TourStatusID);
-- Added CHECK constraint from stage 2 logic
ALTER TABLE TRIP ADD CONSTRAINT chk_enddate CHECK (EndDate IS NULL OR EndDate >= DepartureDate);


-- -- 4. Integrate 'PARTICIPANT' (Equivalent to CUSTOMER) --
ALTER TABLE PARTICIPANT ADD COLUMN JoinDate DATE;


-- -- 5. Integrate 'REGISTRATIONSTATUS' and updates for 'BOOKING' (REGISTRATION in stage 2) --
CREATE TABLE REGISTRATIONSTATUS
(
    RegistrationStatusID INT NOT NULL,
    StatusName VARCHAR(50) NOT NULL,
    PRIMARY KEY (RegistrationStatusID)
);

INSERT INTO REGISTRATIONSTATUS(RegistrationStatusID, StatusName) VALUES(1, 'Needs Action');
INSERT INTO REGISTRATIONSTATUS(RegistrationStatusID, StatusName) VALUES(2, 'Confirmed');
INSERT INTO REGISTRATIONSTATUS(RegistrationStatusID, StatusName) VALUES(3, 'Cancelled');

ALTER TABLE BOOKING ADD COLUMN AmountToPay NUMERIC(8,2) CHECK (AmountToPay >= 0);
ALTER TABLE BOOKING ADD COLUMN Notes VARCHAR(500);
ALTER TABLE BOOKING ADD COLUMN RegistrationStatusID INT;

-- Maps existing string Status to RegistrationStatusID
UPDATE BOOKING SET RegistrationStatusID = 1 WHERE Status = 'Pending';
UPDATE BOOKING SET RegistrationStatusID = 2 WHERE Status = 'Paid';
UPDATE BOOKING SET RegistrationStatusID = 3 WHERE Status = 'Cancelled';

-- Drop the old string column, now obsolete
ALTER TABLE BOOKING DROP COLUMN Status;
ALTER TABLE BOOKING ADD CONSTRAINT fk_booking_regstatus FOREIGN KEY (RegistrationStatusID) REFERENCES REGISTRATIONSTATUS(RegistrationStatusID);


-- -- 6. Integrate 'PAYMENT' system (New domain module from stage 2) --
CREATE TABLE PAYMENTSTATUS
(
    PaymentStatusID INT NOT NULL,
    StatusName VARCHAR(50) NOT NULL,
    PRIMARY KEY (PaymentStatusID)
);

INSERT INTO PAYMENTSTATUS(PaymentStatusID, StatusName) VALUES(1, 'Pending');
INSERT INTO PAYMENTSTATUS(PaymentStatusID, StatusName) VALUES(2, 'Completed');
INSERT INTO PAYMENTSTATUS(PaymentStatusID, StatusName) VALUES(3, 'Failed');
INSERT INTO PAYMENTSTATUS(PaymentStatusID, StatusName) VALUES(4, 'Refunded');

CREATE TABLE PAYMENT
(
    PaymentID INT NOT NULL,
    PaymentDate DATE NOT NULL,
    Amount NUMERIC(8,2) CHECK (Amount >= 0),
    Notes VARCHAR(500),
    PaymentMethod VARCHAR(50) NOT NULL,
    ReferenceNumber VARCHAR(50),
    BookingID INT NOT NULL, -- Links to our native Booking (Their equivalent was Registration)
    PaymentStatusID INT NOT NULL,
    PRIMARY KEY (PaymentID),
    -- Replaced Reference to REGISTRATION with BOOKING to fit merged schema --
    FOREIGN KEY (BookingID) REFERENCES BOOKING(BookingID),
    FOREIGN KEY (PaymentStatusID) REFERENCES PAYMENTSTATUS(PaymentStatusID)
);
*/