-- Stage A: validation queries for all core tables
-- Use this file after running createTables.sql + insertTables.sql

SELECT 'ROUTE' AS table_name, COUNT(*) AS row_count FROM ROUTE
UNION ALL
SELECT 'GUIDE', COUNT(*) FROM GUIDE
UNION ALL
SELECT 'TRIP', COUNT(*) FROM TRIP
UNION ALL
SELECT 'PARTICIPANT', COUNT(*) FROM PARTICIPANT
UNION ALL
SELECT 'BOOKING', COUNT(*) FROM BOOKING
UNION ALL
SELECT 'LOCATION', COUNT(*) FROM LOCATION
UNION ALL
SELECT 'PASSES_THROUGH', COUNT(*) FROM PASSES_THROUGH;

SELECT * FROM ROUTE ORDER BY RouteID LIMIT 10;
SELECT * FROM GUIDE ORDER BY GuideID LIMIT 10;
SELECT * FROM TRIP ORDER BY TripID LIMIT 10;
SELECT * FROM PARTICIPANT ORDER BY ParticipantID LIMIT 10;
SELECT * FROM BOOKING ORDER BY BookingID LIMIT 10;
SELECT * FROM LOCATION ORDER BY LocationID LIMIT 10;
SELECT * FROM PASSES_THROUGH ORDER BY RouteID, LocationID LIMIT 10;
